@startuml C4_container
!include <C4/C4_Container>

title Container diagram - Processing

/' Persons '/
Person(user, "User", "Person who wants easily learn how to create graphic animations or quickly create a prototype.")

/' Containers '/
System_Boundary(processing4, "Processing"){
    Container(pde, "PDE", "Java", "PDE (processing development environment) is the user interface that allows to write and handle a sketch.")
    Container(java_mode, "Java mode", "Java", "Version of the processing language based on Java. It handles all the sketch lifecycle: preprocessing, compilation, built, execution. It offers also the possibility to debug the code and use the tweak mode.")
    Container(sketch_process, "Sketch Process", "Java", "Isolated JVM process that runs the compiled sketch. Hosts the PApplet instance and the active renderer engine.")
    Container(contribution_manager, "Contribution Manager", "Java", "Manages installation, update and removal of libraries, modes, tools and examples.")
}

/' External systems '/ 
System_Ext(os, "Operating system", "It handles the access to the computer's files and to accelerated hardware")
System_Ext(processing_server, "Processing server", "Hosts contributed libraries, modes, tools and release updates.")
System_Ext(external_ide, "External IDE", "External IDE that wants to use the processing language.")

/' User relationships '/
Rel(user, pde, "Writes sketches and triggers execution", "GUI")
Rel(user, java_mode, "Writes commands", "CLI")

/' PDE relationship '/ 
Rel(pde, java_mode, "Delegates compilation and execution control", "Method call")
Rel(pde, os, "File I/O: sketches, preferences, settings", "OS API")
Rel(pde, contribution_manager, "Opens and controls", "Method call")

/' Contribution manager relationship'/
Rel(contribution_manager, processing_server, "Queries catalogue and downloads packages", "HTTPS")
Rel(contribution_manager, os, "Save packages", "OS API")


/' Java mode relationship '/
Rel(java_mode, sketch_process, "Spawns process and communicates runtime messages", "Sockets")
Rel(java_mode, os, "File I/O: temp build files; spawns child JVM", "OS API")

/' Sketch process relationship '/
Rel(sketch_process, os, "Rendering (GPU/CPU), file I/O, native events", "OS API")

/' External IDE '/
Rel(external_ide, java_mode, "Calls the build tools", "CLI")

@enduml