@startuml C4_context
!include <C4/C4_Context>

title Context diagram - Processing 

/' Persons '/
Person(user, "User", "Person who wants easily learn how to create graphic animations or quickly create a prototype.")

/' Systems '/
System(processing4, "Processing", "Software sketchbook and Java-based programming language")
System_Ext(os, "Operating system", "It handles the access to the computer's files and to accelerated hardware")
System_Ext(processing_server, "Processing server", "Hosts contributed libraries, modes, tools and release updates.")
System_Ext(external_ide, "External IDE", "External IDE that wants to use the processing language.")

/' Person relationships '/
Rel(user, processing4, "Writes and executes educational code sketches", "GUI")

/' External component relationships '/
Rel(processing4, os, "Sends data and requests", "OS API")
Rel(processing4, processing_server, "Queries catalogue and downloads packages", "HTTPS")
Rel(external_ide, processing4, "Calls the build tools", "CLI")

@enduml